### PR TITLE
fix current tests

### PR DESCRIPTION
**Pull request by renefritze**
split off from https://github.com/svenevs/exhale/pull/218 with changes not relating to C++ concepts

### CODE REVIEW

**Comment by svenevs** [comment]
Thank you. Brief response between things. I'm clearing Saturday, let's get concepts in. 

This has been approved to run CI. But if it takes you more than a few stabs I'll step in. CI has probably been broken here for a while...

**Comment by renefritze** [comment]
Closing this for now to do trial and error in my fork instead

**Comment by renefritze** [comment]
https://github.com/renefritze/exhale/pull/3

**Comment by renefritze** [comment]
The current tests now all pass in my fork. Couple of notes:

1. I've moved to using the codecov action because the deprecated upload immeadiately ran into rate limiting. 
2. If you're not happy with the new lowest supported version, it's probably not too hard to fix the tests for it. The errors just looked like SPhinx internals that I knew nothing about.
3. I've added a mostly unintrusive pre-commit setup, mostly to get actionlint going. Would you be happy with a more substantial config that also does linting and formatting (with ruff)?
4. Locally the Fortran `CPPFOrtranMixed.tests_hierarchies` fails. For some reason the checked functions have an additional `intent(in)` argument. I've just ignored that. 
5.

**Comment by renefritze** [comment]
Looks like the PR doesn't update from the source branch. I'll try opening a new one instead.

**Pull request closed without merging**
