### PR TITLE
Allow unabridged API to exclude different kinds.

### LINKED ISSUE #64: Exclude Directories and Files?
Is it possible to exclude Directories and Files sections from the unabridged api?

### PR DESCRIPTION
**Pull request by svenevs**
Fixes #64.

- Default to trimming `dir` and `file`.
- Utilize `:orphan:` page attribute (to be continued?).

### CODE REVIEW

**Comment by svenevs** [comment]
@Coderik @TheMaverickProgrammer it ended up being possible to ignore warnings from sphinx about documents not included in any toctree (`:orphan:` page attribute).  This is Option 1 from here since we can get 0 warnings https://github.com/svenevs/exhale/issues/64#issuecomment-494544925

unabridgedOrphanKinds

So basically

1. By default, `dir` and `file` will now be excluded from the full api listing.
2. You can optionally choose more kinds to exclude if you desire.

Note that this does not enable removing a single element from there.  That will be possible in a (somewhat distant) future.  Custom writers will happen at some point, but not until a few other bigger problems can be fixed.

Would you be willing to test this and make sure it does what you want it to?  You can install it (ideally in a virtual environment ;)) with `pip install git+https://github.com/svenevs/exhale.git@fix/unabridged-bury-files-directories`

**Comment by TheMaverickProgrammer** [comment]
This is awesome

**Comment by TheMaverickProgrammer** [comment]
Tried adding your suggested changes and cant get it to build on RTD.

[Link](https://readthedocs.org/projects/battlenetwork/builds/9118648/)
[Raw text](https://readthedocs.org/api/v2/build/9118648.txt)

I added `git+https://github.com/svenevs/exhale.git@fix/unabridged-bury-files-directories` to my `requirements.txt` file.

I reverted back to the last version.

**Comment by svenevs** [comment]
> breathe 4.13.0.post0 has requirement Sphinx>=2.0, but you'll have sphinx 1.8.5 which is incompatible.

I need to update the quickstart / will be adding this in release notes, sorry this wasn't very clear.  Since you are using python3.7 you should require sphinx>=2.0.  In [your `docs/requirements.txt`](https://github.com/TheMaverickProgrammer/battlenetwork/blob/47086874c47443b672d2fd7f5769171be3e8cd90/docs/requirements.txt#L1):

```diff
+ sphinx>=2.0
+ breathe>=4.13.0.post0
- breathe
```

Sphinx 2 drops python 2 support, breathe 4.13.0.post0 drops Sphinx 1.x support.

So for projects that have a specific need to remain on py2, they must pin `sphinx<=1.8.5` and `breathe<=4.12.0`.

Thank you for testing, that is really helpful!

**Comment by TheMaverickProgrammer** [comment]
I'm not getting those sphinx warning anymore but it still fails silently at the same step: [link](https://readthedocs.org/api/v2/build/9124373.txt).

**Comment by TheMaverickProgrammer** [comment]
I see you forked the project... It's pretty big. The branch I'm using on Read The Docs is #windows-linux-merge.

The code on this branch doesn't run correctly so dont expect to play it. It will compile and it is documented.

If you do want to play the game, stick to #master branch as it is stable.

**Comment by TheMaverickProgrammer** [comment]
https://readthedocs.org/api/v2/build/9133256.txt

It seems to be working now. I do see some comments in the conf.py file I don't remember writing. Did you update the file? :D

**Comment by svenevs** [comment]
>  I do see some comments in the conf.py file I don't remember writing

Haha yeah I added some notes in there because I will probably break the hacks that PR added in v1.0, depending on how the writer API comes in.  Meaning you'll trade the hacks in favor of using the writer API.

This branch just got deleted (so you'll need to update your requirements since it's installing a non-existent branch), but this is released on PyPI right now in v0.2.3 :)  AKA require `exhale>=0.2.3`.

Sorry for delay on packaging this, thanks again for helping test it!

**Pull request merged**
