### PR TITLE
Fixed exception while processing missing file definitions.

### PR DESCRIPTION
**Pull request by zz-systems**
While building ZACC documentation, exhale failed during parsing doxygen's XML files. Fixed by converting object (ExhaleNode) to string. Works on my machine after modifying package files (needed a fix ASAP).

Error message:

(!) Exception caught while parsing:Traceback (most recent call last):
File "/usr/local/lib/python3.6/site-packages/exhale/deploy.py", line 378, in explode
textRoot.parse()
File "/usr/local/lib/python3.6/site-packages/exhale/graph.py", line 979, in parse
self.discoverAllNodes()
File "/usr/local/lib/python3.6/site-packages/exhale/graph.py", line 1226, in discoverAllNodes
"{0}{1}".format(bullet, "\n{0}".format(bullet).join(c for c in candidates))
TypeError: sequence item 0: expected str instance, ExhaleNode found

### CODE REVIEW

**Comment by svenevs** [comment]
Whoops -- that's not very helpful!  Your PR looked good, but I went with something a little different.  Can you try the `master` branch as of [`5db06fa5938b18ffa068b10803f45640097955b7`](https://github.com/svenevs/exhale/commit/5db06fa5938b18ffa068b10803f45640097955b7)?

If it's not clear, in testing I never actually ran into this scenario.  I wanted to include the `location` in the print out, which required a different change.  I was also being lazy about building the error message, so I fixed that too.  It should work as expected now.

Thanks for bringing it to my attention!  Please feel free to submit an issue with a link to the docs / the actual error message being printed here.  The "automatic" file definition inference code could probably be better, having a specific use-case would be helpful in determining how it could change.

> needed a fix ASAP

I'm going to update the licenses and fix a couple of links and then release a new version on PyPi if the above commit works for you.  Something on the master that's not released officially is namespace documentation...

**Comment by zz-systems** [comment]
Now, it does not fail anymore during parse XML sequence, but failed with "Path too long" errors during the rst generation. (A filename containing the entire SFINAE sequence in a specialization has been generated).

In my project, I use a lot of template-metaprogramming and had to disable some faulty parts with doxygen commands for now. After those changes, the documentation build process succeeded.

**Comment by svenevs** [comment]
Cool, thanks for the feedback.

> I use a lot of template-metaprogramming and had to disable some faulty parts with doxygen commands for now

Yeah...this has been a particularly uphill battle for me as well.  Though the generated URLs would be less clear for a human, I think I should just change everything to be something like `api/class_{doxygen refid}.rst`.  Template classes are pretty atrocious right now with Exhale :/  Especially the internal links generated...

**Comment by zz-systems** [comment]
> Though the generated URLs would be less clear for a human
I guess, SFINAE is not human-readable :)

**Comment by svenevs** [comment]
Released [in v0.1.6 on PyPi](https://pypi.python.org/pypi/exhale/0.1.6).  Thanks again for bringing up the issue!

I'm getting close to being able to release my own C++ project, which has a lot of SFINAE / meta stuff going on.  I'll be revisiting the naming schemes before that goes public.  Did you want me to ping you when that gets released (v0.1.7)?

**Comment by zz-systems** [comment]
The new exhale release works as expected :) 
Of course, you can ping me so that I can give the new version a try

**Pull request closed without merging**
