### PR TITLE
cleanup testing matrix

### PR DESCRIPTION
**Pull request by svenevs**

### CODE REVIEW

**Comment by svenevs** [comment]
Now I remember what the snag was and why I ultimately chose to have fewer runners that did more python testing internally -- concurrency limits on CI jobs.  Especially once `macOS` gets brought back in, having fewer runners is a better decision.  The thing that takes the longest is actually getting the dev setup (especially doxygen on mac and windows).

**Comment by svenevs** [comment]
Actually, on second thought, I think this is better.  It can always be undone again.

**Comment by svenevs** [comment]
@2bndy5 any thoughts here?  I'm fairly indecisive about this one.  Planning on adding a couple of extras in the future e.g., `black`, waiting for runners can be tedious but at the same time previously what we saw was if it failed on say 2.7 nothing else would run which is also inconvenient.  Input welcome if you have time / any thoughts.  I don't know why I can't request a review from you.

**Comment by 2bndy5** [comment]
I prefer relying on a well written matrix for readability because it helps ease onboarding new contributors/contributions.

I'll take a look at the workflows; I tend to use the events' paths to limit unnecessary workflow runs. That might help relieve the demand for runners.

**Comment by 2bndy5** [comment]
It looks like code coverage mandates all these workflows be run frequently. Although, I don't have intimate knowledge of what code coverage is and what it actually needs to be assessed (especially in the context of this pkg).

That said, I think the _testing_projects.yaml_ might be triggered on only changes to the testing and exhale directories.
```yml
name: Testing Projects
on:
  push:
    branches:
      - master
    paths:
      - testing
      - exhale
  pull_request:
    branches:
      - master
    paths:
      - testing
      - exhale
```

Furthermore, I think maybe the _testing_extras.yaml_ could either be
1. split up into separate workflows that get triggered on certain paths. This seems like overkill (even to me).
2. the jobs could be conditionally run using the `if` option. This can be done with [job level if options](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idif) or with [step level if options](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idstepsif). However, these conditional statements can easily get long-winded and complex, so maybe point 1 might be more appealing.

It would be hard to suggest conditional statements. For example, the docs are likely intertwined in the pkg src's comments and not limited to the docs directory.

**Comment by svenevs** [comment]
closing and reopening to test [rtd pr integration](https://docs.readthedocs.io/en/stable/pull-requests.html)

**Comment by svenevs** [comment]
woah, [this is super cool](https://exhale--132.org.readthedocs.build/en/132/). i'm still contemplating the matrix here but think i will be merging some stuff soon

**Comment by svenevs** [comment]
This is good enough for now ... selection in `.github/workflows/*.yaml` is likely to trip up codecov for PRs that don't trigger things.  Generally, code coverage here is decent but nowhere near complete and therefore not worth using as a selection criteria for blocking a given PR.

If anything, in the future when macOS and problematic doxygen come in, I may just disable some python versions.  Coverage is currently 3.6, 3.7, 3.8, 3.9, 3.10.  But realistically, there aren't any specific features in exhale that would likely break them.  Waiting for runners is probably going to be the choice anyway... AKA i'm over it, this is good enough.

**Pull request merged**
