### PR TITLE
Fix filenames too long.

### LINKED ISSUE #33: Critical error while generating reStructured text files
I'm trying to exhale on a large code base that isn't particularly well documented. The doxygen XML gets created, but the .rst file generation is running into issues with file names that are too long

[+] Exhale: finished parsing Doxygen XML in 20.77 seconds.
[~] Exhale: generating reStructuredText documents.

OSError: [Errno 63] File name too long: (!) Critical error while generating the file for [docs/in/api/function_caffe2__operator_takes_as_input_a_tensor_of_floats_to_find_the_percentile_values_for_COMMA__a_2D_tensor_of_floats_COMMA__where_the_first_column_of_the_tensor_represents_sampled_values_COMMA__and_the_second_column_represents_the_percentile_labels_COMMA__and_a_tensor_of_integers_lengths._This_lengths_tensor_is_used_because_the_operator_works_on_multiple_sets_of_raw_values_at_the_same_time._For_example_COMMA__for_an_input_original_values=_COMMA__lengths=[2_COMMA__1_COMMA__1]_COMMA__value_to_pct=Our_operator_expects_that_each_column_i_of_the_input_tensor_is_sampled_from_distribution_i._Lengths_tells_us_that_the_first_two_elements_in_value_to_pct_are_sampled_from_distribution_1_COMMA__the_next_is_from_distribution_two_COMMA__and_the_last_is_from_distribution_3._We_expect_the_output_of_our_operator_to_give_us_._To_calculate_the_percentile_of_an_element_COMMA__we_check_to_see_if_its_value_is_already_mapped_to_a_percentile_in_value_to_pct._If_so_COMMA__we_return_that_value._If_not_COMMA__we_linearly_interpolate_between_the_two_closest_values_in_value_to_pct._If_the_value_is_larger_than_all_values_in_value_to_pct_COMMA__we_return_1._If_it_'s_smaller_than_all_the_values_COMMA__we_return_0._RPAREN__DOC"_RPAREN__.Input.rst]

I'm not sure where to fix the specfic documentation, or the Doxygen config, or the Sphinx config to allow it to handle this. Is there some way to force it to ignore this particular file and keep building?

### PR DESCRIPTION
**Pull request by svenevs**
Fixes #33.

Reworks how filenames and links are generated.

- [x] Remove absurd "html_safe_name" scheme that embedded all of the template parameters, which causes SFINAE constructs in particular (but more generally, templates with many parameters) to create filenames that trigger an `OSError` because the filename is too long.
- [x] Add some ~simple~ insane tests to the testing framework.
- [x] Add AppVeyor to `codecov` results since there is now officially platform specific code.
- [x] Re-document how to link to generated files.

### CODE REVIEW

**Comment by svenevs** [comment]
@ddemidov @zz-systems this should at least allow Exhale to not crash for SFINAE stuff / large template parameter lists.  This is going to be a minor release bump because if anybody was using the internal links (other than `file` and `dir`) it will break.  The `namespace` links will also break for people.  But technically those were always internal links :wink:

If you have any thoughts they are most welcome before i merge.  I will be adding some simple unit tests to make sure the `255` part definitely works.

**Comment by zz-systems** [comment]
Looking forward to try it :)

**Comment by svenevs** [comment]
> Do you have an estimate of when this can happen? That is, I'd like to know when the updated version will be available on pypi/usable on RTD.

Hopefully by the end of this weekend.  I'm trying to be very careful about _actually_ adding test cases in.  The good news is that once this PR is functional and merged to `master` you won't need to wait for a PyPi release.  I'll include instructions for how to do that here when it is merged :smile:

**Comment by svenevs** [comment]
@ddemidov @zz-systems I am **so sorry** about your inboxes.  Windows really threw me through the ringer here with filesystem limitations I never wanted to learn about, let alone solve.  Exhale can actually generate things that Sphinx will crash on due to the same reasons.  I'll be openning a ticket with them, but anyway...that's what got in the way here.

I am merging this now to `master`, @ddemidov you can add the following to your `requirements.txt` in order to use it on RTD:

```
git+git://github.com/svenevs/exhale.git#egg=exhale
```

If you are willing to test on RTD with your project and respond with a yes or no here as to whether it was successful, I will release a `0.2.0` now.  I will fix the other two small but annoying problems in `0.2.1`, and then resume work on `1.0.0` :smile:  I see no reason not to release this now, provided it works!

**Comment by ddemidov** [comment]
> If you are willing to test on RTD 

Command killed due to excessive memory consumption:
http://readthedocs.org/projects/amgcl/builds/7568399/

The code for the test is: https://github.com/ddemidov/amgcl/tree/docs-exhale/docs

**Comment by ddemidov** [comment]
Yes, local builds are working for me as well. I can wait for the resolution of the breathe issue, thanks for pointing that out.

**Pull request merged**
