### PR TITLE
Handle specialized template functions

### PR DESCRIPTION
**Pull request by hidmic**
Precisely what the title says. It does so by differentiating empty lists of template parameters from no template parameters at all. 

Needs https://github.com/michaeljones/breathe/pull/750 (or `breathe` won't pick specialized template functions to begin with).

### CODE REVIEW

**Comment by hidmic** [comment]
Rebased and ready for a review (if CI comes out green).

CC @svenevs @clalancette

**Comment by svenevs** [comment]
Thanks for reading, I'll look at this soon (as well as remove py2). Do we know what the next version of breathe will be? This requires that so I'm just going to pin

**Comment by svenevs** [comment]
I've got this slated for the weekend since it looks like `breathe==4.32.0` is going to ship.

I think this one fixes a number of issues with templates and believe I get to remove an obnoxious warning :heart:

Will land this ASAP, thanks again for fixing this and breathe!

**Comment by svenevs** [comment]
Sorry for the delay on this.  Will be merging this since it works with the specialized pathological example you added.  I keep looking at this and then desiring to fix the template overloads that are **not** specialized and then getting wound out over it, so unfixed they will remain with a tag to #106 and synopsis that this has to be a breathe bug but I don't think it will be easy for anyone to fix and I at least warn people in the build output.

------------------------------------------------------------

The warning from breathe:

Warning

doxygenfunction: Unable to resolve function “overload::blargh” with arguments (typename C::type) in doxygen xml output for project “cpp_func_overloads” from directory: ./_doxygen/xml. Potential matches:

```
- float blargh(float x)
- float blargh(float x, float y)
- float blargh(float x, float y, float z)
- float blargh(float, float, float, float)
- int blargh(int x)
- int blargh(int x, int y)
- int blargh(int x, int y, int z)
- int blargh(int, int, int, int)
- std::size_t blargh(std::size_t x, const float &y, double z, const std::string &s)
- std::size_t blargh(std::size_t x, const std::string &s)
- std::string blargh(const std::string &x)
- std::string blargh(const std::string &x, const std::string &y)
- std::string blargh(const std::string &x, const std::string &y, const std::string &z)
- std::string blargh(const std::string&, const std::string&, const std::string&, const std::string&)
- template<class C, typename T> std::enable_if<!std::is_convertible<typename C::type, T>::value, T>::type blargh(typename C::type t)
- template<class C, typename T> std::enable_if<std::is_convertible<typename C::type, T>::value, T>::type blargh(typename C::type t)
- template<class C> C::type blargh(typename C::type t)
- void blargh()
- void blargh(const float *x, const float *y, float *z, std::size_t N)
- void blargh(std::vector<std::string> &v)
- void blargh(std::vector<std::vector<int>> &v)
```

Via

```rst
.. _exhale_function_overload_8hpp_1a78c463f6d2e0247e92b6a8cee2dbd86c:

Template Function overload::blargh(typename C::type)
====================================================

- Defined in :ref:`file_include_overload_overload.hpp`


Function Documentation
----------------------


.. doxygenfunction:: overload::blargh(typename C::type)
```

So if I update `breathe_identifier()` to use `full_signature()` for functions:

```rst
.. _exhale_function_overload_8hpp_1a78c463f6d2e0247e92b6a8cee2dbd86c:

Template Function template<class C, typename T> std::enable_if<std::is_convertible<typename C::type, T>::value, T>::type overload::blargh(typename C::type)
===========================================================================================================================================================

- Defined in :ref:`file_include_overload_overload.hpp`


Function Documentation
----------------------

.. this is the one desired
..                   template<class C, typename T> std::enable_if<std::is_convertible<typename C::type, T>::value, T>::type blargh(typename C::type t)

.. doxygenfunction:: template<class C, typename T> std::enable_if<std::is_convertible<typename C::type, T>::value, T>::type overload::blargh(typename C::type)
```

1. It doesn't like having the namespace `overload::blargh` vs `blargh`.
2. It wants `typename C::type t` with defname `t` rather than `typename C::type`.

Alas, even if you give it the exact signature it wants, it does not succeed :cry: A diff that breaks all the other functions (`<declname>` causes problems everywhere else):

```diff
diff --git a/exhale/graph.py b/exhale/graph.py
index 54e57b9..f61319a 100644
--- a/exhale/graph.py
+++ b/exhale/graph.py
@@ -268,10 +268,11 @@ class ExhaleNode(object):
         """
         if self.kind == "function":
             # TODO: breathe bug with templates and overloads, don't know what to do...
-            return "{name}({parameters})".format(
-                name=self.name,
-                parameters=", ".join(self.parameters)
-            )
+            # return "{name}({parameters})".format(
+            #     name=self.name,
+            #     parameters=", ".join(self.parameters)
+            # )
+            return self.full_signature()
 
         return self.name
 
@@ -290,9 +291,9 @@ class ExhaleNode(object):
         """
         if self.kind == "function":
             return "{template}{return_type} {name}({parameters})".format(
-                template="template <{0}> ".format(", ".join(self.template)) if self.template is not None else "",
+                template="template<{0}> ".format(", ".join(self.template)) if self.template is not None else "",
                 return_type=self.return_type,
-                name=self.name,
+                name=self.name.split("::")[-1],
                 parameters=", ".join(self.parameters)
             )
         raise RuntimeError(
@@ -2164,8 +2165,13 @@ class ExhaleRoot(object):
                 # 2. The function parameter list.
                 parameters = []
                 for param in memberdef.find_all("param", recursive=False):
-                    parameters.append(param.type.text)
-                func.parameters = utils.sanitize_all(parameters)
+                    p = utils.sanitize(param.type.text)
+                    if param.declname:
+                        p += " " + param.declname.text
+                    parameters.append(p)
+
+                func.parameters = parameters
+
                 # 3. The template parameter list.
                 templateparamlist = memberdef.templateparamlist
                 if templateparamlist:
```

**Pull request merged**
