### PR TITLE
Update dependencies according to breathe==4.35.0

### LINKED ISSUE #202: Problem with Sphinx 7
## Problem

Exhale fails to run with sphinx 7 because the requirements does not allow the latest exhale version to be installed:

> install_requires =
    # From breathe==4.32.0
    Sphinx>=3.0,<7

For this reason `pip` installs an older exhale version 0.2.4 which is incompatible with sphinx 7.

## Solution

Allow exhale 0.3.6 to run with sphinx 7. Tested and works (sphinx==7.2.6).

Fixed by #200

### PR DESCRIPTION
**Pull request by Rotzbua**
### Change

* Breaking: Remove support of sphinx 3.x
* Update dependencies according to breathe==4.35.0

Fixes  #202

### CODE REVIEW

**Comment by Chrismarsh** [comment]
Just noting that this is blocking C++ code doc generation on RTD for me, and having [PR#205](https://github.com/svenevs/exhale/pull/205) merged would be fantastic.

**Comment by svenevs** [comment]
Thanks @Chrismarsh , fast response from a phone while out. I set a reminder to give this project some attention this weekend, please poke me by Sunday to get a new release out if I haven't gotten it done this week (a lot of stuff going on already...)

**Comment by Chrismarsh** [comment]
Thanks @svenevs . The work on the project is much apprecaited! 
For anyone else running into this problem  like #203 and #202 is to use this PR directly in your requirements
`exhale @ git+https://github.com/svenevs/exhale.git@refs/pull/205/merge`

**Comment by svenevs** [comment]
@Chrismarsh I released 0.3.7.... I broke CI (#212), please let me know if the official release actually works for you :pray:

**Comment by Chrismarsh** [comment]
Ah great! I'm afk this week and will try it next week and let you know!

**Comment by svenevs** [comment]
No problem, thanks for the response! I think if I had broken everything somebody probably would have raised an issue by now 🙃 But you'll likely want to set your requirements to `exhale>=0.3.7` at some point so feedback that it works would be much appreciated.

**Comment by Chrismarsh** [comment]
@svenevs just made the change and built on RTD. Confirmed `exhale==0.3.7` was pulled. All seems to "just work" as expected. Thanks!

**Comment by svenevs** [comment]
Hooray! Thanks for following up and letting me know 🙃

**Pull request closed without merging**
